### ISSUE TITLE
build.sh --clean doesn't work

### ISSUE THREAD

**Issue by GrantEdwards** [Azure/azure-iot-gateway-sdk#120]
The build.sh --clean option appears to be ignored.  There doesn't seem to be any way to rebuild
sources.

**Comment by damonbarry** [comment]
Yeah, `--clean` was part of the original build script, but didn't see much use and eventually went stale. The right thing to do is to remove it, since the build script deletes the cmake `build/` folder every time (i.e., every build is a clean build).

If you've already built and you want to rebuild the gateway bits without calling the build script, the way to do it in Linux is (from the repo root folder):
```
cd build/
make clean
make
```

If you're talking about rebuilding everything including dependencies, there's a flag in the latest build script for that: `--rebuild-deps`.

**Comment by damonbarry** [comment]
Fix is in the [2017-03-06](https://github.com/Azure/azure-iot-gateway-sdk/tree/2017-03-06) release.
