### ISSUE TITLE
Question: build.cmd fails on deps build

### ISSUE THREAD

**Issue by WilliamBerryiii** [Azure/azure-iot-gateway-sdk#181]
Ran into an interesting issue today with a Win10 machine running the latest cmake & latest git from an admin VS2017 dev cmd prompt; the script consistently fails on executing and building the nanomsg lib. and all subsequent ones.  Doing a recursive clone and then running with rebuild-deps, allowed the build to complete.

**Comment by damonbarry** [comment]
@WilliamBerryiii We don't support building for Visual Studio 2014 from a **VS2017** dev cmd prompt. We also don't yet support building for Visual Studio 2017; I'm working on that right now.

Also, if the `--rebuild-deps` argument fixed whatever your problem was, then you likely had an inconsistency in your environment to begin with (e.g., you previously built for x86 and now you're trying to build for x64, or release vs. debug, or something similar...).

**Comment by WilliamBerryiii** [comment]
@damonbarry thanks for the info.

**Comment by damonbarry** [comment]
@WilliamBerryiii FYI, I checked in support for VS2017 on Friday (commit: c1687a8839ea78dedbe77cb96fa6909a79f1d246). Check it out!

**Comment by WilliamBerryiii** [comment]
@damonbarry sweet! will do.
