### ISSUE TITLE
build module in my own folders

### ISSUE THREAD

**Issue by Kevin0626** [Azure/azure-iot-gateway-sdk#225]
Hi, currently the module samples are built under the open source root folder. We want to have own folder out of the open source tree for developing modules. Any suggestion to setup the build script and cmake files?

Ideally we don't want to change the build.sh and cmake files under the azure-iot-gateway-sdk. however we only least change option to to modify the cmake file under the root folder and add add_subdirectory() command in the bottom.

**Comment by damonbarry** [comment]
If you're developing modules in Java, Node.js, or .NET, then your best option is to install one of our packages from Maven, npm, or NuGet. Check out this repo, which shows examples of sample modules created with our packages: https://github.com/Azure-Samples/azure-iot-gateway-samples.

If you want to build the SDK from source, then you'll want to use CMake to install the headers/libraries after you build. Once you've installed the SDK, you can create your own project (completely independent of our source tree), and reference the gateway libs/headers from your project like any other dependency.

To build and install the gateway SDK (e.g., on Windows), do this:

Open a Developer Command Prompt for VS2017 (or VS2015) **as Administrator** (this is because you'll be installing things to `C:\Program Files`).
Run the following command from the root of the gateway SDK repo:
```
tools\build.cmd --platform x64 --config Release --system-deps-path
```
Note: `--system-deps-path` installs our dependencies (like the [Azure IoT Device SDK](https://github.com/Azure/azure-iot-sdk-c)) to `C:\Program Files`.

When that is finished, change to the `build` directory and use CMake to install the gateway bits:
```
cd build
cmake --build . --target install
```
When this is complete, the gateway SDK will be installed at `C:\Program Files\azure_iot_gateway_sdk-1.x.x`. You can link `lib/gateway.lib` and include `include/` in your project.

The process is similar on Linux or Mac.

**Comment by Kevin0626** [comment]
Thanks for the detailed instructions. We just have one more question. 

We have need to build multiple target platforms. When we build and install the SDK, can we specify the platform subfolder for the installation path? for example, C:\Program Files\azure_iot_gateway_sdk-1.x.x\[platform]

**Comment by damonbarry** [comment]
Unfortunately, we don't right now. :(
Would you mind creating a new issue to track that? I don't know how soon we'll be able to get to it, but it would certainly be a good thing to do.

**Comment by Kevin0626** [comment]
sure, thanks!

**Comment by Kevin0626** [comment]
I found the azure gateway installation doesn't include the c-utility open source header files. The user module still need to refer to the utility header files. 

I try to build and install the c-utility open source, unfortunately it looks the header files are not copied to some installation path.

**Comment by damonbarry** [comment]
Following my steps above, each of our dependencies are installed to their own folder under `C:\Program Files`. So the include path for the c-utility headers is `C:\Program Files\azure_c_shared_utility\include\azureiot`.

**Comment by Kevin0626** [comment]
Yes, you are right.  I tested it on Linux and didn't specify the "--system-deps-path" parameter, the installation path for the depended components is the "install-deps" under the source tree folder.

Thank you again!
