### ISSUE TITLE
[.NET Binding][Improvement] Use preferred types for interop

### ISSUE THREAD

**Issue by yfakariya** [Azure/azure-iot-gateway-sdk#23]
(separated from #20)
Use `IntPtr` instead of `long` for pointer or handle types in the surface between managed code and native code. This solves a potential marshaling problem when the gw sdk runs in x86 or arm32 in the future.

**Comment by damonbarry** [comment]
Thanks for reporting this! Sorry for the delay, we plan to fix this soon.

**Comment by damonbarry** [comment]
@yfakariya: in our C code we're converting module/broker pointers to `long long` (always 64 bits). We're sending the 64-bit values to the C# Broker constructor, which takes C# `long` arguments (always 64 bits).

So on 64-bit platforms everything should work nicely. And on 32-bit platforms, the 32-bit pointer values will be promoted to 64-bits, and then everything should work nicely. All the pointer values originate in native code, and all pointer access happens in native code; they're simply used as opaque identifiers in the managed code.

So I may be overlooking something important...is there really a problem with using a 64-bit integer instead of IntPtr here?

**Comment by yfakariya** [comment]
Sorry I missed casting to `long long` in C code. I agree it is no problem. Thanks!
