### ISSUE TITLE
Source file encoding should be UTF-8 instead of Latin-1

### ISSUE THREAD

**Issue by yfakariya** [Azure/azure-iot-gateway-sdk#30]
I noticed that following files are saved as Latin-1 encoding, so it causes compilation error because of "treating warning as error" when the developer uses non Latin-1 code page console in Windows:

* deps/azure-c-shared-utility/inc/azure_c_shared_utility/xlogging.h
* deps/azure-iot-sdks/c/azure-uamqp-c/src/connection.c
* deps/azure-iot-sdks/c/azure-uamqp-c/src/frame_codec.c
* deps/azure-iot-sdks/c/azure-uamqp-c/src/saslclientio.c
* deps/azure-iot-sdks/c/azure-uamqp-c/src/sasl_frame_codec.c
* deps/azure-iot-sdks/c/azure-uamqp-c/tests/connection_ut/connection_ut.cpp
* deps/azure-iot-sdks/c/azure-uamqp-c/tests/frame_codec_ut/frame_codec_ut.cpp
* deps/azure-iot-sdks/c/azure-uamqp-c/tests/sasl_frame_codec_ut/sasl_frame_codec_ut.cpp
* deps/azure-iot-sdks/c/azure-uamqp-c/tests/saslclientio_ut/saslclientio_ut.cpp
* deps/azure-iot-sdks/c/iothub_client/src/iothubtransportmqtt.c
* deps/azure-iot-sdks/c/iothub_client/tests/iothubtransportmqtt_ut/iothubtransportmqtt_ut.cpp

I think this is NOT gateway SDK's matter, but I don't know best approach to tell this issue for each team...

**Comment by damonbarry** [comment]
@yfakariya Sorry for the delay...can you file these issues in the azure-c-shared-utility and azure-iot-sdks repos, so we can track them more easily?  Thanks!

**Comment by yfakariya** [comment]
Sure! Thank you for teach me proper repos.

**Comment by yphuangms** [comment]
Does change code page inside command prompt (before running build.cmd) resolve the issue?
>chcp 437

**Comment by yfakariya** [comment]
No, I still got C2220 errors.
It looks that  Visual C++ compiler uses cp932 internally from OS's locale setting (and just try to out messages with cp437 and fails to output).

**Comment by yphuangms** [comment]
Surfed the internet looking for solutions and with no luck. It seems VS developer command prompt doesn't take the result of "chcp" command, even if we do "chcp" inside VS developer command prompt script as first line in "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\VsDevCmd.bat". 

The only solution for now is to change OS "region" setting to "United States". This makes the default command prompt code page set to 437.

Since release "2016-11-18", the build process has changed to build upon prebuilt dep lib and include files, so there's no such errors any more, for those invalid Latin-1 characters are mostly from Azure IoT Device SDK source code.
