### ISSUE TITLE
[Build Error][module_loader_ut][Windows] Build failed at "core/tests/module_loader_ut" due to "java_module_host.h" not found.

### ISSUE THREAD

**Issue by yphuangms** [Azure/azure-iot-gateway-sdk#55]
When build unit test program for "module_loader_ut", it cause the build process abort due to build error. The error indicates "java_module_host.h" not found. 

The fix to this error is to add a include path in "core/tests/module_loader_ut/CMakeLists.txt"

   include_directories(${GW_INC})
   include_directories(../../../bindings/java/inc)

**Comment by andrew-buckley** [comment]
Hi @yphuangms, this has already been fixed and is in both the develop and master branches.

**Comment by yphuangms** [comment]
Is it possible to tag a fixed version as "release" version? (and remove "2016-11-18", because this released version is failed to build)

Just download the latest one instead of the released "2016-11-18", and seemed like the problem is fixed by removing all the defines to enable bindings in CMakeLists.txt.
This could temporarily fix the problem, but it just fix the problem by preventing this unit test of module_load_ut from testing loader related functions, because all the defines that will enable the loader test are removed from CMakeLists.txt. Those definition has to be bring back into CMakeLists.txt and add condition to enable these defines like this:

if(${enable_java_binding})
    add_definitions(-DJAVA_BINDING_ENABLED)
endif()
if(${enable_dotnet_binding})
    add_definitions(-DDOTNET_BINDING_ENABLED)
endif()
if(${enable_nodejs_binding})
    add_definitions(-DNODE_BINDING_ENABLED)
endif()

**Comment by andrew-buckley** [comment]
Those add_definitions happen. If you look at this [CMakeLists.txt](https://github.com/Azure/azure-iot-gateway-sdk/blob/master/core/CMakeLists.txt) file.

**Comment by avranju** [comment]
The fix doesn't prevent the unit tests from running. It causes the module loader unit tests to include the loader for a given language binding only when that language binding has been enabled during the build. Our CI builds always run all the tests with all the bindings enabled (that is in fact the reason why this issue went undetected because it crops up only when you build without any of the language bindings enabled).

As Andrew mentioned, when a given language binding is enabled the corresponding loader test will also run.

**Comment by damonbarry** [comment]
We release to master every two weeks now that the SDK is generally available. We plan to release at the end of the coming week (around Fri Dec 16th), so we'll have a tagged release at that point which contains the fix.
