### ISSUE TITLE
Running and Debugging in an IDE --> Dev Experience

### ISSUE THREAD

**Issue by vslepakov** [Azure/azure-iot-gateway-sdk#80]
From what I've seen so far all samples deal with building and running on cli.
Is it possible/going to be possible to develop/run/debug in Eclipse/Visual Studio?
It would probably mean starting the gateway process from within the IDE etc.

**Comment by andrew-buckley** [comment]
Hi @vslepakov, you can run, develop, and debug the gateway in Visual Studio. Just open the solution file after using CMake to generate the project. You may also debug Java modules in any Java IDE of your choice using the remote debugging support for Java modules in the gateway. Please let me know if you'd like more info on remote Java module debugging.

**Comment by vslepakov** [comment]
Hi @andrew-buckley, thanks for that information. I would really appreciate some more input on remote Java module debugging

**Comment by stefangordon** [comment]
Similar experience - the layout of the repo and build baffles me so far.  The best I can tell you are expected to fork this repo and hack directly in it (using the entire SDK as a sample, rather than a component which can be versioned and updated).  

I went ahead and hand built project files for everything based on the generated ones, and pulled in the bits I needed to make a single clean solution that builds/runs/debugs with a single F5 in visual studio - but when new bits are released it will be challenging to merge them.

I'd be curious to know how the maintainers would approach building a new project on various platforms, without editing this repository.  I can imagine you could make it work pulling in this repo as a sub module but it would be a bit ugly.

Or perhaps there is a plan to restructure or break into multiple repositories at a later date.

**Comment by darobs** [comment]
Hi @stefangordon - this is definitely still a work in progress.  We are working towards releasing the SDK as a package (like the C SDK is released as a NuGet package and a Debian package).

As an intermediate step, we set up the gateway SDK and its IoT C SDK dependencies to be installable in either a system folder or local to the repo.  I installed the libraries to the system directory as a test, and was able to create a simple gateway outside the repo in a few lines of CMake:

```
cmake_minimum_required(VERSION 2.8.12)
project(simpleGW)

find_package(azure_iot_gateway_sdk REQUIRED CONFIG)

#main gateway
set(sgw_sources main.c sgw.json)
add_executable(sgw ${sgw_sources})
target_link_libraries(sgw gateway)

# module
set(sgw_module_sources sgw_module.h sgw_module.c)
add_library(sgw_module MODULE ${sgw_module_sources})
target_link_libraries(sgw_module gateway)
```
This created a solution which builds/runs/debugs with a single F5.  This is stepping point to a better developer experience, and we are continuing to work on making it better.

Thanks for your interest,
Dave

**Comment by stefangordon** [comment]
Excellent info, Thanks!

**Comment by andrew-buckley** [comment]
@vslepakov, please have a look at the sample gateway configuration file [here](https://github.com/Azure/azure-iot-gateway-sdk/blob/master/samples/java_sample/src/java_sample_win.json) for the java sample. In the loaders section you may specify different jvm options for the java module loader. You should add these two additional options to the **jvm.options** section to enable remote debugging:
```
"jvm.options":{
...
"debug": true,
"debug.port": <port of your choosing>
...
}
```

Next, in the Java IDE of your choosing, you should open your java module project and setup remote debugging however it is done for that particular IDE with the same debug port that you specified in the configuration file. Next you should be able to start running the gateway, it will wait for the debugger to attach when you start debugging from your IDE. Let me know if this works for you!

**Comment by damonbarry** [comment]
It looks like all outstanding questions here have been resolved. Closing...
