### ISSUE TITLE
Unable to get the right event data to the IoT Hub

### ISSUE THREAD

**Issue by aaxan** [Azure/azure-iot-gateway-sdk#84]
Running the "simulated_device_cloud_upload_sample" (as described in https://docs.microsoft.com/en-gb/azure/iot-hub/iot-hub-windows-gateway-sdk-simulated-device), I didn't get the expected result:
1. In the Device Explorer of the IoT Hub, the Event Hub Data shows that the Properties are not built correctly:
29/12/2016 22:35:28> Device: [DeviceB], Data:[{"temperature": 15.00}]Properties:
'source': 'mapping'
2. In a Stream Analytics job (Microsoft Azure Portal), no events are found for the input from the IoT Hub. Sometimes a warning is shown for this input: 
"Could not deserialize the input event as Json. Some possible reasons: 1) Malformed events 2) Input source configured with incorrect serialization format".

Could you please give me any hints to this issue?

**Comment by damonbarry** [comment]
@aaxan when you say 

> the Properties are not built correctly

what do you mean? Did you expect to see certain properties in the output, but they aren't there? Or is the JSON syntax not what you expect?

It would be great to see an example of expected output alongside the actual output.

**Comment by aaxan** [comment]
At the 1. issue in my comment I put the log message I get in the Device Explorer of the IoT Hub, this is e.g.
29/12/2016 22:35:28> Device: [DeviceB], Data:[{"temperature": 15.00}]Properties:
 'source': 'mapping'

It means that the event was received from the device "DeviceB", the data in JSON format is {"temperature": 15.00}. After that, it looks like the message above isn't formed correctly, e.g. no comma before the word "Properties", the part after the ":" character isn't included between "[" and "]".  I suppose that this could be the reason, why I get in the Stream Analytics job the warning as mention in 2. issue of my comment.

**Comment by damonbarry** [comment]
The Device Explorer tool doesn't make any attempt to JSON-format the "Event Hub Data" output in the Data tab. The fact that `Properties: 'source': 'mapping'` doesn't contain square brackets doesn't matter because `Properties` is not a JSON name, it's just a hard-coded label in the UI. The fact that the device name (`DeviceB`) and the message payload (`{"temperature": 15.00}`) are surrounded in square brackets `[]` is also just a hard-coded convention in the UI. In this particular case, the only part of the message that is JSON-formatted is the payload.

If you can see messages landing in IoT Hub (e.g. via the Device Explorer tool), then the sample is doing its job. If you created a Stream Analytics job and your query isn't finding any events, then you probably need to investigate your query (e.g., make sure `SELECT *` works, then refine it from there).
